// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const cardListContainer: string;
export const cardContainer: string;
export const imageLinkViewContainer: string;
export const gatsbyImage: string;
export const embedContainer: string;
export const hoverOverlay: string;
export const cardSongPreview: string;
export const cardInfo: string;
